/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_isans_cris_CRISAndroid */

#ifndef _Included_com_isans_cris_CRISAndroid
#define _Included_com_isans_cris_CRISAndroid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    GetState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_isans_cris_CRISAndroid_GetState
  (JNIEnv *, jobject);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    GetProcessRate
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_isans_cris_CRISAndroid_GetProcessRate
  (JNIEnv *, jobject);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    GetVendorID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_isans_cris_CRISAndroid_GetVendorID
  (JNIEnv *, jobject);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    Initialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_isans_cris_CRISAndroid_Initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    MoveForward
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_isans_cris_CRISAndroid_MoveForward
  (JNIEnv *, jobject);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    MoveBackward
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_isans_cris_CRISAndroid_MoveBackward
  (JNIEnv *, jobject);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    TurnLeft
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_isans_cris_CRISAndroid_TurnLeft
  (JNIEnv *, jobject);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    TurnRight
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_isans_cris_CRISAndroid_TurnRight
  (JNIEnv *, jobject);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    MoveDelta
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_isans_cris_CRISAndroid_MoveDelta
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    TurnDelta
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_isans_cris_CRISAndroid_TurnDelta
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    GoToPose
 * Signature: (DDD)Z
 */
JNIEXPORT jboolean JNICALL Java_com_isans_cris_CRISAndroid_GoToPose
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    Stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_isans_cris_CRISAndroid_Stop
  (JNIEnv *, jobject);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    SetLed
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_isans_cris_CRISAndroid_SetLed
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    Command
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_isans_cris_CRISAndroid_Command
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    MoveDeltaB
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_isans_cris_CRISAndroid_MoveDeltaB
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    TurnDeltaB
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_isans_cris_CRISAndroid_TurnDeltaB
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    GoToPoseB
 * Signature: (DDD)Z
 */
JNIEXPORT jboolean JNICALL Java_com_isans_cris_CRISAndroid_GoToPoseB
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    SetMaxVelocity
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_isans_cris_CRISAndroid_SetMaxVelocity
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    GetMaxVelocity
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_isans_cris_CRISAndroid_GetMaxVelocity
  (JNIEnv *, jobject);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    SetMaxAcceleration
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_isans_cris_CRISAndroid_SetMaxAcceleration
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    GetMaxAcceleration
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_isans_cris_CRISAndroid_GetMaxAcceleration
  (JNIEnv *, jobject);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    SetVelocity
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_isans_cris_CRISAndroid_SetVelocity
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    GetVelocity
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_isans_cris_CRISAndroid_GetVelocity
  (JNIEnv *, jobject);

/*
 * Class:     com_isans_cris_CRISAndroid
 * Method:    GetMap
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_isans_cris_CRISAndroid_GetMap
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
